"""Unified visualization primitives for single-cell OmicsClaw skills."""

from .core import QC_PALETTE, apply_singlecell_theme, save_figure
from .embedding import (
    embedding_axis_labels,
    make_categorical_palette,
    plot_cluster_qc_heatmap,
    plot_cluster_size_summary,
    plot_embedding_categorical,
    plot_embedding_comparison,
    plot_embedding_continuous,
)
from .annotation import (
    plot_cell_type_count_barplot,
    plot_cluster_annotation_heatmap,
)
from .markers import (
    plot_marker_cluster_summary,
    plot_marker_dotplot,
    plot_marker_effect_summary,
    plot_marker_fraction_scatter,
    plot_marker_heatmap,
)
from .de import (
    plot_de_effect_summary,
    plot_de_group_summary,
    plot_de_rank_panels,
)
from .enrichment import (
    plot_enrichment_embedding_panels,
    plot_group_mean_dotplot,
    plot_group_mean_heatmap,
    plot_pathway_score_distributions,
    plot_top_gene_sets_bar,
)
from .stat_enrichment import (
    compute_running_score_curve,
    plot_enrichment_enrichmap,
    plot_enrichment_group_summary,
    plot_enrichment_group_term_dotplot,
    plot_enrichment_ridgeplot,
    plot_enrichment_top_terms_bar,
    plot_gsea_running_score_panels,
)
from .doublet import (
    plot_doublet_call_summary,
    plot_doublet_score_by_group,
    plot_doublet_score_distribution,
)
from .qc import (
    plot_barcode_rank,
    plot_highest_expr_genes,
    plot_qc_correlation_heatmap,
    plot_qc_histograms,
    plot_qc_scatter,
    plot_qc_violin,
)
from .upstream import (
    plot_barcode_rank,
    plot_count_complexity_scatter,
    plot_count_scatter,
    plot_count_distributions,
    plot_filter_metric_comparison,
    plot_filter_reason_summary,
    plot_filter_retention_summary,
    plot_filter_state_scatter,
    plot_filter_threshold_panels,
    plot_fastq_file_quality,
    plot_fastq_per_base_quality,
    plot_fastq_read_structure,
    plot_fastq_sample_summary,
    plot_velocity_gene_balance,
    plot_velocity_layer_fraction,
    plot_velocity_layer_summary,
    plot_velocity_magnitude_distribution,
    plot_velocity_top_genes_bar,
    plot_velocity_top_genes_stacked,
    plot_latent_time_distribution,
)

__all__ = [
    "QC_PALETTE",
    "apply_singlecell_theme",
    "save_figure",
    "embedding_axis_labels",
    "make_categorical_palette",
    "plot_embedding_categorical",
    "plot_embedding_comparison",
    "plot_embedding_continuous",
    "plot_cell_type_count_barplot",
    "plot_cluster_annotation_heatmap",
    "plot_cluster_size_summary",
    "plot_cluster_qc_heatmap",
    "plot_marker_heatmap",
    "plot_marker_dotplot",
    "plot_marker_effect_summary",
    "plot_marker_fraction_scatter",
    "plot_marker_cluster_summary",
    "plot_de_effect_summary",
    "plot_de_group_summary",
    "plot_de_rank_panels",
    "plot_top_gene_sets_bar",
    "plot_group_mean_heatmap",
    "plot_group_mean_dotplot",
    "plot_pathway_score_distributions",
    "plot_enrichment_embedding_panels",
    "plot_enrichment_top_terms_bar",
    "plot_enrichment_group_term_dotplot",
    "plot_enrichment_group_summary",
    "plot_enrichment_enrichmap",
    "plot_enrichment_ridgeplot",
    "compute_running_score_curve",
    "plot_gsea_running_score_panels",
    "plot_doublet_score_distribution",
    "plot_doublet_call_summary",
    "plot_doublet_score_by_group",
    "plot_qc_violin",
    "plot_qc_scatter",
    "plot_qc_histograms",
    "plot_highest_expr_genes",
    "plot_barcode_rank",
    "plot_qc_correlation_heatmap",
    "plot_fastq_sample_summary",
    "plot_fastq_file_quality",
    "plot_fastq_per_base_quality",
    "plot_fastq_read_structure",
    "plot_count_distributions",
    "plot_count_complexity_scatter",
    "plot_count_scatter",
    "plot_filter_metric_comparison",
    "plot_filter_threshold_panels",
    "plot_filter_state_scatter",
    "plot_filter_reason_summary",
    "plot_filter_retention_summary",
    "plot_barcode_rank",
    "plot_velocity_layer_summary",
    "plot_velocity_layer_fraction",
    "plot_velocity_gene_balance",
    "plot_velocity_top_genes_bar",
    "plot_velocity_top_genes_stacked",
    "plot_velocity_magnitude_distribution",
    "plot_latent_time_distribution",
]
