"""Unified visualization primitives for single-cell OmicsClaw skills."""

from .core import QC_PALETTE, apply_singlecell_theme, save_figure
from .embedding import (
    embedding_axis_labels,
    make_categorical_palette,
    plot_cluster_qc_heatmap,
    plot_cluster_size_summary,
    plot_embedding_categorical,
    plot_embedding_comparison,
)
from .qc import (
    plot_barcode_rank,
    plot_highest_expr_genes,
    plot_qc_correlation_heatmap,
    plot_qc_histograms,
    plot_qc_scatter,
    plot_qc_violin,
)
from .upstream import (
    plot_barcode_rank,
    plot_count_complexity_scatter,
    plot_count_scatter,
    plot_count_distributions,
    plot_filter_metric_comparison,
    plot_filter_reason_summary,
    plot_filter_retention_summary,
    plot_filter_state_scatter,
    plot_filter_threshold_panels,
    plot_fastq_file_quality,
    plot_fastq_per_base_quality,
    plot_fastq_read_structure,
    plot_fastq_sample_summary,
    plot_velocity_gene_balance,
    plot_velocity_layer_fraction,
    plot_velocity_layer_summary,
    plot_velocity_magnitude_distribution,
    plot_velocity_top_genes_bar,
    plot_velocity_top_genes_stacked,
    plot_latent_time_distribution,
)

__all__ = [
    "QC_PALETTE",
    "apply_singlecell_theme",
    "save_figure",
    "embedding_axis_labels",
    "make_categorical_palette",
    "plot_embedding_categorical",
    "plot_embedding_comparison",
    "plot_cluster_size_summary",
    "plot_cluster_qc_heatmap",
    "plot_qc_violin",
    "plot_qc_scatter",
    "plot_qc_histograms",
    "plot_highest_expr_genes",
    "plot_barcode_rank",
    "plot_qc_correlation_heatmap",
    "plot_fastq_sample_summary",
    "plot_fastq_file_quality",
    "plot_fastq_per_base_quality",
    "plot_fastq_read_structure",
    "plot_count_distributions",
    "plot_count_complexity_scatter",
    "plot_count_scatter",
    "plot_filter_metric_comparison",
    "plot_filter_threshold_panels",
    "plot_filter_state_scatter",
    "plot_filter_reason_summary",
    "plot_filter_retention_summary",
    "plot_barcode_rank",
    "plot_velocity_layer_summary",
    "plot_velocity_layer_fraction",
    "plot_velocity_gene_balance",
    "plot_velocity_top_genes_bar",
    "plot_velocity_top_genes_stacked",
    "plot_velocity_magnitude_distribution",
    "plot_latent_time_distribution",
]
