"""Shared runtime primitives for OmicsClaw adapters."""

from .bot_tools import BotToolContext, build_bot_tool_registry, build_bot_tool_specs
from .context_budget import estimate_message_size, trim_history_to_budget
from .context_assembler import (
    AssembledChatContext,
    PromptContextAssembly,
    assemble_chat_context,
    assemble_prompt_context,
    build_user_message_content,
    extract_analysis_hints,
    extract_user_text,
    message_mentions_term,
    should_attach_capability_context,
)
from .context_layers import (
    DEFAULT_CONTEXT_LAYER_INJECTORS,
    DEFAULT_SOUL_MD,
    ContextAssemblyRequest,
    ContextLayer,
    ContextLayerInjector,
    get_default_context_injectors,
    get_skill_contract,
    load_base_persona,
)
from .query_engine import (
    QueryEngineCallbacks,
    QueryEngineConfig,
    QueryEngineContext,
    run_query_engine,
)
from .system_prompt import build_system_prompt, get_role_guardrails
from .task_store import (
    DONE_TASK_STATUSES,
    TASK_STATUS_BLOCKED,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_PENDING,
    TASK_STATUS_SKIPPED,
    TaskRecord,
    TaskStore,
)
from .tool_orchestration import ToolExecutionRequest, ToolExecutionResult, execute_tool_requests
from .tool_result_store import ToolResultRecord, ToolResultStore
from .tool_registry import ToolRegistry, ToolRuntime
from .tool_spec import ToolSpec
from .transcript_store import (
    AdvisoryEventRef,
    CompactedToolResultRef,
    PlanReference,
    TranscriptReplaySummary,
    TranscriptStore,
    TranscriptSummary,
    build_selective_replay_context,
    build_selective_replay_summary,
    build_transcript_summary,
    extract_advisory_event_refs,
    extract_compacted_tool_result_refs,
    extract_plan_references,
    sanitize_tool_history,
)
from .verification import (
    ARTIFACT_KIND_DIR,
    ARTIFACT_KIND_FILE,
    COMPLETION_REPORT_FILENAME,
    COMPLETION_STATUS_AWAITING_APPROVAL,
    COMPLETION_STATUS_COMPLETE,
    COMPLETION_STATUS_FAILED,
    COMPLETION_STATUS_INCOMPLETE,
    COMPLETION_STATUS_PARTIAL,
    WORKSPACE_KIND_ANALYSIS_RUN,
    WORKSPACE_KIND_CONVERSATION,
    ArtifactRequirement,
    ArtifactVerification,
    CompletionReport,
    build_completion_report,
    format_completion_mapping_summary,
    format_completion_summary,
    isolated_workspace,
    update_workspace_manifest,
    verify_workspace_artifacts,
    write_completion_report,
)

__all__ = [
    "AssembledChatContext",
    "BotToolContext",
    "ContextAssemblyRequest",
    "ContextLayer",
    "ContextLayerInjector",
    "QueryEngineCallbacks",
    "QueryEngineConfig",
    "QueryEngineContext",
    "DEFAULT_CONTEXT_LAYER_INJECTORS",
    "DEFAULT_SOUL_MD",
    "AdvisoryEventRef",
    "DONE_TASK_STATUSES",
    "PlanReference",
    "PromptContextAssembly",
    "TASK_STATUS_BLOCKED",
    "TASK_STATUS_COMPLETED",
    "TASK_STATUS_FAILED",
    "TASK_STATUS_IN_PROGRESS",
    "TASK_STATUS_PENDING",
    "TASK_STATUS_SKIPPED",
    "TaskRecord",
    "TaskStore",
    "ToolResultRecord",
    "ToolResultStore",
    "ToolExecutionRequest",
    "ToolExecutionResult",
    "ToolRegistry",
    "ToolRuntime",
    "ToolSpec",
    "CompactedToolResultRef",
    "CompletionReport",
    "COMPLETION_REPORT_FILENAME",
    "COMPLETION_STATUS_AWAITING_APPROVAL",
    "COMPLETION_STATUS_COMPLETE",
    "COMPLETION_STATUS_FAILED",
    "COMPLETION_STATUS_INCOMPLETE",
    "COMPLETION_STATUS_PARTIAL",
    "TranscriptReplaySummary",
    "TranscriptSummary",
    "TranscriptStore",
    "ARTIFACT_KIND_DIR",
    "ARTIFACT_KIND_FILE",
    "ArtifactRequirement",
    "ArtifactVerification",
    "WORKSPACE_KIND_ANALYSIS_RUN",
    "WORKSPACE_KIND_CONVERSATION",
    "assemble_chat_context",
    "assemble_prompt_context",
    "build_transcript_summary",
    "build_completion_report",
    "build_bot_tool_registry",
    "build_bot_tool_specs",
    "format_completion_mapping_summary",
    "build_system_prompt",
    "build_selective_replay_context",
    "build_selective_replay_summary",
    "build_user_message_content",
    "estimate_message_size",
    "execute_tool_requests",
    "extract_analysis_hints",
    "extract_advisory_event_refs",
    "extract_compacted_tool_result_refs",
    "extract_plan_references",
    "extract_user_text",
    "format_completion_summary",
    "get_default_context_injectors",
    "get_role_guardrails",
    "get_skill_contract",
    "isolated_workspace",
    "load_base_persona",
    "message_mentions_term",
    "sanitize_tool_history",
    "should_attach_capability_context",
    "trim_history_to_budget",
    "update_workspace_manifest",
    "verify_workspace_artifacts",
    "write_completion_report",
    "run_query_engine",
]
