#!/usr/bin/env python3
"""Generate ``skills/<domain>/INDEX.md`` — the lazy-load detail file.

The ``omicsclaw`` bot tool description contains a compact 7-domain briefing
(see ``omicsclaw.skill.domain_briefing``). When the LLM needs the full skill
list for one domain, it follows the briefing's hint and reads
``skills/<domain>/INDEX.md`` — which this script regenerates from the
registry. Keeping INDEX files on disk (vs. returning from a tool call) lets
them be cached by the prompt cache and viewed by humans in the repo.

Output format per line::

    - `skill-alias` — description text
      triggers: keyword1, keyword2, keyword3

Usage::

    python scripts/generate_domain_index.py            # preview one file
    python scripts/generate_domain_index.py --apply    # write all files
    python scripts/generate_domain_index.py --check    # exit 1 on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from omicsclaw.skill.registry import OmicsRegistry, SKILLS_DIR  # noqa: E402

_MAX_TRIGGERS_PER_SKILL = 8

_DOMAIN_ORDER = (
    "spatial",
    "singlecell",
    "genomics",
    "proteomics",
    "metabolomics",
    "bulkrna",
    "orchestrator",
)


def _domain_dir(domain_key: str) -> Path:
    return SKILLS_DIR / domain_key


def _collect_domain_skills(reg: OmicsRegistry) -> dict[str, list[tuple[str, dict]]]:
    """Group canonical skills by domain for rendering."""
    grouped: dict[str, list[tuple[str, dict]]] = {}
    for alias, info in reg.skills.items():
        if info.get("alias") != alias:  # skip legacy alias duplicates
            continue
        domain = info.get("domain") or "unknown"
        grouped.setdefault(domain, []).append((alias, info))
    for rows in grouped.values():
        rows.sort(key=lambda kv: kv[0])
    return grouped


def _render_domain_index(
    domain_key: str, skills: list[tuple[str, dict]], reg: OmicsRegistry
) -> str:
    domain_info = reg.domains.get(domain_key) or {}
    display_name = domain_info.get("name", domain_key)
    summary = (domain_info.get("summary") or "").strip()
    primary_types = ", ".join(domain_info.get("primary_data_types") or [])

    lines: list[str] = [
        f"# {display_name} — Skill Index",
        "",
        "> Auto-generated by `scripts/generate_domain_index.py`.",
        "> Do not edit by hand — changes will be overwritten.",
        "",
        f"**Domain key:** `{domain_key}`  ",
        f"**Skill count:** {len(skills)}  ",
    ]
    if primary_types:
        lines.append(f"**Primary data types:** {primary_types}  ")
    if summary:
        lines.extend(["", summary])
    lines.extend(["", "## Skills", ""])

    for alias, info in skills:
        desc = (info.get("description") or "").strip().replace("\n", " ")
        triggers = list(info.get("trigger_keywords") or [])[:_MAX_TRIGGERS_PER_SKILL]
        lines.append(f"- `{alias}` — {desc}" if desc else f"- `{alias}`")
        if triggers:
            trig_text = ", ".join(triggers)
            lines.append(f"  triggers: {trig_text}")

    lines.append("")
    return "\n".join(lines)


def _planned_files() -> dict[Path, str]:
    """Return {output_path: rendered_text} for every domain with skills."""
    reg = OmicsRegistry()
    reg.load_all()
    reg.load_lightweight()
    grouped = _collect_domain_skills(reg)

    out: dict[Path, str] = {}
    for domain_key in _DOMAIN_ORDER:
        skills = grouped.get(domain_key)
        if not skills:
            continue
        out_path = _domain_dir(domain_key) / "INDEX.md"
        if not out_path.parent.exists():
            continue
        out[out_path] = _render_domain_index(domain_key, skills, reg)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate skills/<domain>/INDEX.md"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--apply", action="store_true", help="Write all INDEX.md files")
    group.add_argument(
        "--check", action="store_true", help="Exit 1 if any INDEX.md is out of date"
    )
    args = parser.parse_args()

    files = _planned_files()

    if args.check:
        drifted: list[Path] = []
        for path, expected in files.items():
            current = path.read_text() if path.exists() else ""
            if current.rstrip() != expected.rstrip():
                drifted.append(path)
        if drifted:
            rel = [str(p.relative_to(ROOT)) for p in drifted]
            print(
                "ERROR: the following domain INDEX.md files are out of date:\n"
                + "\n".join(f"  - {p}" for p in rel)
                + "\nRun: python scripts/generate_domain_index.py --apply",
                file=sys.stderr,
            )
            return 1
        print(f"All {len(files)} domain INDEX.md files are up to date.")
        return 0

    if args.apply:
        changed = 0
        for path, expected in files.items():
            current = path.read_text() if path.exists() else ""
            if current != expected:
                path.write_text(expected)
                changed += 1
        print(f"Wrote {len(files)} INDEX.md files ({changed} changed).")
        return 0

    # Preview mode: print one domain as a sample.
    sample = next(iter(files.items()), None)
    if sample is None:
        print("No domains to render.")
        return 0
    path, text = sample
    print(f"# Preview: {path.relative_to(ROOT)}\n")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
