#!/usr/bin/env python3
"""Auto-generate the Skill Routing Table section of CLAUDE.md.

Reads skill metadata from the Registry (dual-track v1/v2 via LazySkillMetadata) and generates
markdown tables grouped by domain.  Replaces the content between
``<!-- ROUTING-TABLE-START -->`` and ``<!-- ROUTING-TABLE-END -->`` markers.

Usage:
    python scripts/generate_routing_table.py              # preview to stdout
    python scripts/generate_routing_table.py --apply      # write to CLAUDE.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from omicsclaw.skill.registry import OmicsRegistry, SKILLS_DIR, _HARDCODED_DOMAINS

START_MARKER = "<!-- ROUTING-TABLE-START -->"
END_MARKER = "<!-- ROUTING-TABLE-END -->"

CLAUDE_MD = _ROOT / "CLAUDE.md"

# Domain display order and human-readable names
DOMAIN_ORDER = [
    ("spatial", "Spatial Transcriptomics"),
    ("singlecell", "Single-Cell Omics"),
    ("genomics", "Genomics"),
    ("proteomics", "Proteomics"),
    ("metabolomics", "Metabolomics"),
    ("bulkrna", "Bulk RNA-seq"),
    ("orchestrator", "Orchestration"),
]


def _skill_path_display(script_path: Path) -> str:
    """Convert a script path to a display path like ``skills/spatial/spatial-preprocess/``."""
    try:
        rel = script_path.parent.relative_to(SKILLS_DIR)
        return f"skills/{rel}/"
    except ValueError:
        return f"skills/{script_path.parent.name}/"


def _build_user_intent(lazy_meta, description: str) -> str:
    """Build the User Intent column from trigger_keywords or description."""
    if lazy_meta and lazy_meta.trigger_keywords:
        kws = lazy_meta.trigger_keywords
        # Limit to 8 keywords for readability
        if len(kws) > 8:
            kws = kws[:8]
        return ", ".join(kws)
    # Fallback: use description
    return description


def _generate_full_tables() -> str:
    """Generate the full per-domain routing tables (legacy / ``--full`` mode)."""
    reg = OmicsRegistry()
    reg.load_all()
    reg.load_lightweight()

    lines: list[str] = []

    for domain_key, domain_display in DOMAIN_ORDER:
        domain_skills: list[tuple[str, dict]] = []
        for alias, info in reg.skills.items():
            if info.get("domain") != domain_key:
                continue
            if info.get("alias") != alias:
                continue
            domain_skills.append((alias, info))

        if not domain_skills:
            continue

        count = len(domain_skills)
        lines.append(f"### {domain_display} ({count} skills)")
        lines.append("")
        lines.append("| User Intent | Skill | Action |")
        lines.append("|---|---|---|")

        for alias, info in domain_skills:
            script = info.get("script")
            if not script:
                continue
            skill_path = _skill_path_display(Path(script))
            dir_name = Path(script).parent.name
            lazy = reg.lazy_skills.get(dir_name)
            intent = _build_user_intent(lazy, info.get("description", alias))
            action = f"Run `python omicsclaw.py run {alias}`"
            lines.append(f"| {intent} | `{skill_path}` | {action} |")

        lines.append("")

    return "\n".join(lines)


def _generate_briefing() -> str:
    """Generate a compact 7-domain briefing (default, token-cheap mode).

    Uses ``omicsclaw.skill.domain_briefing`` as the single source of truth so
    the CLAUDE.md briefing and the bot-tool briefing stay byte-identical.
    Appends a single ``| domain | count | INDEX link |`` lookup table so a
    human (or LLM) can jump to the full list of any domain.
    """
    from omicsclaw.skill.domain_briefing import build_domain_briefing

    briefing = build_domain_briefing(
        lead_in=(
            "When the user asks an analysis question, match it to a skill and act. "
            "OmicsClaw covers 7 domains; pick one, then consult its INDEX for the "
            "full skill list if the briefing below isn't enough."
        ),
        trailing_hint="",
    )

    reg = OmicsRegistry()
    reg.load_all()
    grouped: dict[str, int] = {}
    for alias, info in reg.skills.items():
        if info.get("alias") != alias:
            continue
        domain = info.get("domain")
        if not domain:
            continue
        grouped[domain] = grouped.get(domain, 0) + 1

    lookup_rows = [
        "",
        "### Full per-domain skill list",
        "",
        "| Domain | Skills | Full index |",
        "|---|---|---|",
    ]
    for domain_key, display in DOMAIN_ORDER:
        n = grouped.get(domain_key)
        if not n:
            continue
        lookup_rows.append(
            f"| {display} | {n} | [`skills/{domain_key}/INDEX.md`](skills/{domain_key}/INDEX.md) |"
        )
    lookup_rows.append("")
    lookup_rows.append(
        "> Auto-generated by `scripts/generate_routing_table.py`. "
        "Pass `--full` to emit the legacy per-skill routing tables inline."
    )
    lookup_rows.append("")

    return briefing + "\n" + "\n".join(lookup_rows)


def generate_tables(full: bool = False) -> str:
    """Return the routing block content.

    By default returns the compact 7-domain briefing (~600 tokens).
    Pass ``full=True`` to restore the legacy 88-row per-skill tables
    (~4,300 tokens) for cases where the full listing is desired in context.
    """
    return _generate_full_tables() if full else _generate_briefing()


def apply_to_claude_md(table_content: str) -> bool:
    """Replace the routing table section in CLAUDE.md between markers."""
    if not CLAUDE_MD.exists():
        print(f"ERROR: {CLAUDE_MD} not found", file=sys.stderr)
        return False

    content = CLAUDE_MD.read_text(encoding="utf-8")

    start_idx = content.find(START_MARKER)
    end_idx = content.find(END_MARKER)

    if start_idx == -1 or end_idx == -1:
        print(f"ERROR: Markers not found in {CLAUDE_MD}", file=sys.stderr)
        print(f"  Expected: {START_MARKER} ... {END_MARKER}")
        return False

    # Replace between markers (keep markers themselves)
    new_content = (
        content[: start_idx + len(START_MARKER)]
        + "\n\n"
        + table_content
        + content[end_idx:]
    )

    CLAUDE_MD.write_text(new_content, encoding="utf-8")
    return True


def _would_change(table_content: str) -> bool:
    """Return True if applying ``table_content`` would modify CLAUDE.md."""
    if not CLAUDE_MD.exists():
        return True
    content = CLAUDE_MD.read_text(encoding="utf-8")
    start_idx = content.find(START_MARKER)
    end_idx = content.find(END_MARKER)
    if start_idx == -1 or end_idx == -1:
        return True
    expected = (
        content[: start_idx + len(START_MARKER)]
        + "\n\n"
        + table_content
        + content[end_idx:]
    )
    return content != expected


def main():
    parser = argparse.ArgumentParser(description="Generate CLAUDE.md routing table")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--apply", action="store_true", help="Write to CLAUDE.md")
    group.add_argument("--check", action="store_true", help="Exit 1 if CLAUDE.md is out of date")
    parser.add_argument(
        "--full",
        action="store_true",
        help="Emit the legacy full 88-row per-skill tables instead of the compact 7-domain briefing",
    )
    args = parser.parse_args()

    table = generate_tables(full=args.full)

    if args.check:
        if _would_change(table):
            print(
                "ERROR: CLAUDE.md routing table is out of date.\n"
                "       Run: python scripts/generate_routing_table.py --apply",
                file=sys.stderr,
            )
            sys.exit(1)
        print("CLAUDE.md routing table is up to date.")
        return

    if args.apply:
        if apply_to_claude_md(table):
            print(f"Updated {CLAUDE_MD}")
            row_count = sum(1 for line in table.splitlines() if line.startswith("|") and "User Intent" not in line and "---" not in line)
            print(f"  {row_count} skill rows across {len(DOMAIN_ORDER)} domains")
        else:
            sys.exit(1)
    else:
        print(table)


if __name__ == "__main__":
    main()
