#!/usr/bin/env python3
"""Migrate a legacy OmicsClaw skill to the v2 layout.

Per-skill workflow (the maintainer is in the loop):

    $ python scripts/migrate_skill.py skills/<domain>/<skill>
    # ... wrote parameters.yaml, SKILL.md.new, references/, _migration/
    $ # review _migration/{gotcha-candidates,description-suggestions}.md
    $ # hand-edit SKILL.md.new (Gotchas, description, When-to-use)
    $ rm skills/<domain>/<skill>/SKILL.md
    $ mv skills/<domain>/<skill>/SKILL.md.new SKILL.md
    $ rm -r skills/<domain>/<skill>/_migration
    $ python scripts/skill_lint.py skills/<domain>/<skill>

Original SKILL.md is never overwritten.  All migration artefacts carry a
provenance header so a maintainer can trace what came from where.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import yaml

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))
sys.path.insert(0, str(_ROOT / "scripts"))

from generate_parameters_md import render_parameters_md  # noqa: E402

# ---------------------------------------------------------------------------
# Heading buckets — which legacy headings flow into which references file
# ---------------------------------------------------------------------------

METHODOLOGY_HEADINGS = (
    "algorithm", "methodology", "workflow", "design validation",
    "lfc shrinkage", "transformation guidance", "core capabilities",
    "input formats", "version compatibility", "dependencies",
)
OUTPUT_HEADINGS = ("output structure", "output schema", "output contract",
                   "outputs", "result", "visualization contract")
R_VIZ_HEADINGS = ("r enhanced", "r visualization", "r visualisation", "replot")
SAFETY_HEADINGS = ("safety",)
DROP_HEADINGS = ("citations", "related skills", "example queries",
                 "integration with orchestrator", "why this exists",
                 "parameters")  # Parameters becomes auto-generated md

# ---------------------------------------------------------------------------
# Gotcha mining patterns
# ---------------------------------------------------------------------------

GOTCHA_PATTERNS = (
    # Lead-boundary only: many patterns end in `:` which is itself a non-word
    # character, so a trailing `\b` would never match.
    re.compile(r"\b(falls back to|fallback to|fails when|requires (>=|at least|the)|"
               r"do not|must not|note:|warning:|important:|caveat:?|gotcha:?|"
               r"only relevant for|incompatible with)", re.IGNORECASE),
)


def _provenance_header(source: Path, kind: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- Generated by scripts/migrate_skill.py at {ts} -->\n"
        f"<!-- Kind: {kind} | Source: {source.name} -->\n\n"
    )


# ---------------------------------------------------------------------------
# SKILL.md parsing
# ---------------------------------------------------------------------------

def _parse_skill_md(skill_md: Path) -> tuple[dict, str]:
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    return yaml.safe_load(parts[1]) or {}, parts[2].lstrip("\n")


def _split_body_into_sections(body: str) -> list[tuple[str, str]]:
    """Split markdown body into (heading, content) pairs.

    A "section" begins at a `## ` line (h2) and runs to the next h2 or EOF.
    Content before the first h2 is returned with heading "".
    """
    sections: list[tuple[str, str]] = []
    current_heading = ""
    current_lines: list[str] = []
    for line in body.splitlines(keepends=True):
        if line.startswith("## "):
            sections.append((current_heading, "".join(current_lines)))
            current_heading = line[3:].strip()
            current_lines = [line]
        else:
            current_lines.append(line)
    sections.append((current_heading, "".join(current_lines)))
    return sections


def _classify_heading(heading: str) -> str:
    h = heading.lower()
    for keyword in METHODOLOGY_HEADINGS:
        if keyword in h:
            return "methodology"
    for keyword in OUTPUT_HEADINGS:
        if keyword in h:
            return "output_contract"
    for keyword in R_VIZ_HEADINGS:
        if keyword in h:
            return "r_visualization"
    for keyword in SAFETY_HEADINGS:
        if keyword in h:
            return "safety"
    for keyword in DROP_HEADINGS:
        if keyword in h:
            return "drop"
    return "methodology"  # default bucket — keeps content rather than losing it


# ---------------------------------------------------------------------------
# Sidecar extraction
# ---------------------------------------------------------------------------

# Default values for sidecar fields when the legacy block omits them.
SIDECAR_DEFAULTS: dict[str, object] = {
    "saves_h5ad": False,
    "requires_preprocessed": False,
    "trigger_keywords": [],
    "legacy_aliases": [],
    "allowed_extra_flags": [],
    "param_hints": {},
}


def _build_sidecar(legacy_omicsclaw: dict) -> dict:
    """Copy every key from the legacy `metadata.omicsclaw` block verbatim,
    then ensure required fields have their defaults filled in.  Decorative
    fields (`homepage`, `os`, `install`, `requires`) flow through unchanged
    even though no current runtime code reads them — preserving data is
    cheaper than re-deriving it later."""
    sidecar = dict(legacy_omicsclaw)
    sidecar.setdefault("domain", "")
    sidecar.setdefault("script", "")
    for key, default in SIDECAR_DEFAULTS.items():
        sidecar.setdefault(key, default)
    return sidecar


# ---------------------------------------------------------------------------
# SKILL.md.new generation
# ---------------------------------------------------------------------------

def _build_thin_frontmatter(legacy_fm: dict) -> dict:
    keep = ("name", "description", "version", "author", "license", "tags", "requires")
    return {k: legacy_fm[k] for k in keep if k in legacy_fm}


def _build_v2_body(skill_name: str, legacy_body: str) -> str:
    """Skeleton body — the maintainer fills it in by referencing the
    untouched original SKILL.md and the _migration/ aids."""
    return (
        f"# {skill_name}\n\n"
        "## When to use\n\n"
        "<!-- TODO(migration): one paragraph mirroring the new "
        "'Load when... Skip when...' description above. -->\n\n"
        "## Inputs & Outputs\n\n"
        "<!-- TODO(migration): one-line input + output rows. "
        "Detailed schema lives in references/output_contract.md. -->\n\n"
        "## Flow\n\n"
        "<!-- TODO(migration): <=7 bullets summarising the runtime path. "
        "Algorithm details are in references/methodology.md. -->\n\n"
        "## Gotchas\n\n"
        "<!-- TODO(migration): see _migration/gotcha-candidates.md "
        "for mined seeds; accept/edit them here. Append-only flywheel. -->\n\n"
        "- _No gotchas yet — append entries as they surface in production._\n\n"
        "## Key CLI\n\n"
        "<!-- TODO(migration): show the demo invocation + one realistic "
        "invocation. Full flag list lives in references/parameters.md. -->\n\n"
        "## See also\n\n"
        "- `references/parameters.md` — every CLI flag and tuning hint\n"
        "- `references/methodology.md` — algorithm and design decisions\n"
        "- `references/output_contract.md` — output directory layout\n"
    )


def _dump_skill_md(frontmatter: dict, body: str) -> str:
    return (
        "---\n"
        + yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=True)
        + "---\n\n"
        + body
    )


# ---------------------------------------------------------------------------
# References slicing
# ---------------------------------------------------------------------------

def _write_references(skill_dir: Path, legacy_body: str, sidecar: dict) -> None:
    refs_dir = skill_dir / "references"
    refs_dir.mkdir(exist_ok=True)

    sections = _split_body_into_sections(legacy_body)
    buckets: dict[str, list[str]] = {
        "methodology": [], "output_contract": [], "r_visualization": []
    }
    for heading, content in sections:
        if not heading:
            continue  # preamble — leave it; the new SKILL.md owns the lead-in
        bucket = _classify_heading(heading)
        if bucket == "safety":
            # "Safety And Guardrails" content carries real failure-mode info
            # that the maintainer will likely promote to ## Gotchas.  Route
            # it into methodology rather than silently drop.
            buckets["methodology"].append(content)
        elif bucket in buckets:
            buckets[bucket].append(content)

    skill_md = skill_dir / "SKILL.md"
    for name, parts in buckets.items():
        target = refs_dir / f"{name}.md"
        if parts:
            target.write_text(
                _provenance_header(skill_md, kind=f"references/{name}.md")
                + "\n".join(parts).rstrip() + "\n",
                encoding="utf-8",
            )
        elif name in ("methodology", "output_contract"):
            # required references — write a stub so skill_lint passes after
            # the maintainer drops the legacy content.
            target.write_text(
                _provenance_header(skill_md, kind=f"references/{name}.md")
                + f"# {name.replace('_', ' ').title()}\n\n"
                "<!-- TODO(migration): legacy SKILL.md had no matching "
                "section. Fill in. -->\n",
                encoding="utf-8",
            )

    # parameters.md — auto-generated from the sidecar
    (refs_dir / "parameters.md").write_text(render_parameters_md(sidecar), encoding="utf-8")


# ---------------------------------------------------------------------------
# _migration/ aids
# ---------------------------------------------------------------------------

_EMPHASIS_RE = re.compile(r"\*+|_+")


def _normalise_for_mining(line: str) -> str:
    """Strip markdown blockquote/list/emphasis decoration so pattern
    matching sees the underlying text.  `> **Note**: ...` is the dominant
    warning shape across OmicsClaw's legacy SKILL.md files."""
    line = line.lstrip(" >").strip(" -*")
    return _EMPHASIS_RE.sub("", line)


def _mine_gotchas(legacy_body: str, tests_dir: Path) -> list[str]:
    candidates: list[str] = []
    for line in legacy_body.splitlines():
        cleaned = _normalise_for_mining(line)
        if not cleaned:
            continue
        if any(p.search(cleaned) for p in GOTCHA_PATTERNS):
            candidates.append(cleaned)

    if tests_dir.exists():
        for test_file in tests_dir.glob("test_*.py"):
            for match in re.finditer(r"def (test_\w*(?:_when_|_falls_back|_fails)\w*)",
                                     test_file.read_text(encoding="utf-8")):
                candidates.append(f"(from {test_file.name}) {match.group(1)}")
    return candidates


def _write_migration_aids(
    skill_dir: Path,
    legacy_fm: dict,
    legacy_body: str,
) -> None:
    aids = skill_dir / "_migration"
    aids.mkdir(exist_ok=True)
    skill_md = skill_dir / "SKILL.md"

    gotchas = _mine_gotchas(legacy_body, skill_dir / "tests")
    gotcha_text = (
        _provenance_header(skill_md, kind="gotcha-candidates")
        + "# Gotcha candidates\n\n"
        + "Mined from the legacy SKILL.md body and tests/.  Accept, edit, or "
        "drop each entry as you fill in the `## Gotchas` section of "
        "SKILL.md.new.\n\n"
    )
    if gotchas:
        for c in gotchas:
            gotcha_text += f"- {c}\n"
    else:
        gotcha_text += "_(no candidates mined)_\n"
    (aids / "gotcha-candidates.md").write_text(gotcha_text, encoding="utf-8")

    old_desc = legacy_fm.get("description", "")
    tags = legacy_fm.get("tags", []) or []
    suggestions = (
        _provenance_header(skill_md, kind="description-suggestions")
        + "# Description rewrite\n\n"
        f"## Legacy description\n\n> {old_desc}\n\n"
        "## Suggested 'Load when... Skip when...' templates\n\n"
        f"1. Load when the user wants to {tags[0] if tags else '<verb> <noun>'}; "
        "skip when <neighbouring skill applies>.\n"
        "2. Load when <user-language phrasing>. Skip if <input shape mismatch>.\n"
        "3. Load when <expected upstream output is present>; skip if running before "
        "<prerequisite skill>.\n\n"
        "Pick one and rewrite by hand — the suggestions above are just scaffolding.\n"
        f"Tags for context: {tags}\n"
    )
    (aids / "description-suggestions.md").write_text(suggestions, encoding="utf-8")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def migrate(skill_dir: Path) -> None:
    """Migrate one skill in-place.

    Side effects: writes parameters.yaml, SKILL.md.new, references/*.md, and
    _migration/*.md.  Does NOT touch the original SKILL.md.
    """
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        raise FileNotFoundError(f"{skill_dir}: SKILL.md not found")

    legacy_fm, legacy_body = _parse_skill_md(skill_md)
    legacy_omicsclaw = (legacy_fm.get("metadata") or {}).get("omicsclaw") or {}

    sidecar = _build_sidecar(legacy_omicsclaw)
    (skill_dir / "parameters.yaml").write_text(
        yaml.safe_dump(sidecar, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    skill_md_new = _dump_skill_md(
        _build_thin_frontmatter(legacy_fm),
        _build_v2_body(legacy_fm.get("name", skill_dir.name), legacy_body),
    )
    (skill_dir / "SKILL.md.new").write_text(skill_md_new, encoding="utf-8")

    _write_references(skill_dir, legacy_body, sidecar)
    _write_migration_aids(skill_dir, legacy_fm, legacy_body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("skill_dir", type=Path)
    args = parser.parse_args()

    try:
        migrate(args.skill_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"migrated: {args.skill_dir}")
    print("  - wrote parameters.yaml")
    print("  - wrote SKILL.md.new (review + rename to SKILL.md when ready)")
    print("  - wrote references/{methodology,output_contract,r_visualization,parameters}.md")
    print("  - wrote _migration/{gotcha-candidates,description-suggestions}.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
