"""Lazy-load skill-list rendering used by the ``list_skills_in_domain`` tool.

Purpose
-------
The bot's ``omicsclaw`` tool description carries a compact 8-domain briefing
(``omicsclaw.skill.domain_briefing``) — intentionally small so every turn pays
~500 tokens instead of ~4,000. When the briefing isn't enough for the LLM to
pick a skill, it calls ``list_skills_in_domain(domain=...)`` to page in the
full listing for a single domain. This keeps always-loaded context small and
only spends tokens when routing actually needs detail.

The function is deliberately pure: it reads the registry and formats markdown.
It does NOT touch disk (even though ``skills/<domain>/INDEX.md`` exists on
disk — generated by ``scripts/generate_domain_index.py``). Reading from the
live registry avoids any staleness surface if the generator hasn't been run
after a skill addition.
"""

from __future__ import annotations

from typing import Iterable

from .registry import registry

_MAX_TRIGGERS_SHOWN = 8
_MAX_DESC_CHARS = 180


def _matches_filter(alias: str, description: str, triggers: Iterable[str], needle: str) -> bool:
    """Case-insensitive substring match across alias / description / triggers."""
    if not needle:
        return True
    hay = alias.lower() + " \x00 " + description.lower()
    for t in triggers:
        hay += " \x00 " + str(t).lower()
    return needle in hay


def _collect_domain_skills(domain: str) -> list[tuple[str, dict]]:
    """Return canonical (alias, info) pairs for the given domain, sorted by alias."""
    out: list[tuple[str, dict]] = []
    for alias, info in registry.skills.items():
        # Skip legacy-alias duplicates: only the canonical key has alias == its own key.
        if info.get("alias") != alias:
            continue
        if info.get("domain") != domain:
            continue
        out.append((alias, info))
    out.sort(key=lambda kv: kv[0])
    return out


def list_skills_in_domain(
    domain: str,
    filter: str = "",
    *,
    ensure_loaded: bool = True,
) -> str:
    """Render a markdown skill list for one domain.

    Parameters
    ----------
    domain:
        Domain key — one of ``spatial``, ``singlecell``, ``genomics``,
        ``proteomics``, ``metabolomics``, ``bulkrna``, ``orchestrator``,
        ``literature``.
        Unknown domains return a short error-style message (NOT an exception)
        so the LLM can recover without a crash path.
    filter:
        Optional case-insensitive substring match. Applied across alias,
        description, and trigger keywords. Empty string = no filter.
    ensure_loaded:
        If True, call ``registry.load_all()`` first. Tests can pass False to
        skip disk I/O when the registry is pre-populated.
    """
    if ensure_loaded:
        registry.load_all()

    domain = (domain or "").strip().lower()
    if domain not in registry.domains:
        known = ", ".join(sorted(registry.domains.keys()))
        return (
            f"Unknown domain: `{domain!r}`. Known domains: {known}.\n\n"
            "Tip: call this tool with `domain='spatial'` / `'singlecell'` / ...,"
            " or re-invoke `omicsclaw` with `skill='auto'` + a natural-language `query`."
        )

    domain_info = registry.domains[domain]
    display_name = domain_info.get("name", domain)
    summary = (domain_info.get("summary") or "").strip()

    skills = _collect_domain_skills(domain)
    needle = filter.strip().lower()

    matched: list[tuple[str, dict, list[str]]] = []
    for alias, info in skills:
        desc = (info.get("description") or "").strip()
        triggers = list(info.get("trigger_keywords") or [])
        if _matches_filter(alias, desc, triggers, needle):
            matched.append((alias, info, triggers))

    header = [f"# {display_name} — {len(matched)}/{len(skills)} skills"]
    if summary:
        header.append("")
        header.append(summary)
    if needle:
        header.append("")
        header.append(f"**Filter:** `{filter}` (case-insensitive substring match)")
    header.append("")

    if not matched:
        header.append(
            "No skills match that filter. Drop the `filter` parameter to see "
            "the full domain list, or try different keywords."
        )
        return "\n".join(header)

    lines = [*header, "## Skills", ""]
    for alias, info, triggers in matched:
        desc = (info.get("description") or "").strip().replace("\n", " ")
        if len(desc) > _MAX_DESC_CHARS:
            desc = desc[: _MAX_DESC_CHARS - 1].rstrip() + "…"
        lines.append(f"- `{alias}` — {desc}" if desc else f"- `{alias}`")
        if triggers:
            shown = triggers[:_MAX_TRIGGERS_SHOWN]
            lines.append(f"  triggers: {', '.join(shown)}")

    lines.extend([
        "",
        f"**Next step:** call `omicsclaw` with `skill='<chosen alias above>'` "
        "and the user's data. Prefer `skill='auto'` with a `query` when the "
        "briefing alone is enough — this tool is only for disambiguation.",
    ])
    return "\n".join(lines)


__all__ = ["list_skills_in_domain"]
