"""Post-run output processing: rename, README, reproducibility notebook.

After the skill subprocess exits successfully the runner needs to:

1. Optionally rename the auto-generated output directory to include the
   actual method that was used (``spatial-domains__cellcharter__20260329_063000``).
2. Write a human-readable ``README.md`` summarising what ran.
3. Emit a reproducibility notebook from ``result.json``.

Pipeline runs also emit a top-level ``README.md`` that lists each step's
status / method / output — that helper lives here too so all post-run
artifact generation is in one file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from omicsclaw.common.report import (
    build_output_dir_name,
    extract_method_name,
    load_result_json,
    write_output_readme,
)


def _get_write_analysis_notebook():
    """Late-import the notebook writer to keep the import graph shallow."""
    from omicsclaw.common.notebook_export import write_analysis_notebook

    return write_analysis_notebook


def deduplicate_path(path: Path) -> Path:
    """Append ``_1``, ``_2`` ... until the path becomes unique."""
    if not path.exists():
        return path
    i = 1
    while True:
        candidate = path.with_name(f"{path.name}_{i}")
        if not candidate.exists():
            return candidate
        i += 1


def finalize_output_directory(
    out_dir: Path,
    *,
    skill_name: str,
    skill_info: dict[str, Any],
    timestamp: str,
    user_supplied_output_dir: bool,
    preferred_method: str | None = None,
    actual_command: list[str] | None = None,
) -> tuple[Path, str | None, str, str, dict[str, Any] | None]:
    """Rename autogenerated output dirs and generate human-readable artifacts.

    Returns ``(final_dir, actual_method, readme_path, notebook_path, payload)``.
    """
    payload = load_result_json(out_dir)
    actual_method = extract_method_name(payload, fallback=preferred_method)
    final_dir = out_dir
    notebook_command = list(actual_command) if actual_command else None

    if not user_supplied_output_dir and actual_method:
        desired_name = build_output_dir_name(skill_name, timestamp, method=actual_method)
        desired_path = deduplicate_path(out_dir.with_name(desired_name))
        if desired_path != out_dir:
            try:
                out_dir.rename(desired_path)
                final_dir = desired_path
            except OSError:
                final_dir = out_dir

    if notebook_command:
        for idx, token in enumerate(notebook_command):
            if token == "--output" and idx + 1 < len(notebook_command):
                notebook_command[idx + 1] = str(final_dir)
                break

    notebook_path = _get_write_analysis_notebook()(
        final_dir,
        skill_alias=skill_name,
        description=skill_info.get("description", ""),
        result_payload=payload,
        preferred_method=actual_method,
        script_path=skill_info.get("script"),
        actual_command=notebook_command,
    )
    readme_path = write_output_readme(
        final_dir,
        skill_alias=skill_name,
        description=skill_info.get("description", ""),
        result_payload=payload,
        preferred_method=actual_method,
        notebook_path=notebook_path,
    )
    return final_dir, actual_method, str(readme_path), str(notebook_path), payload


def write_pipeline_readme(
    output_dir: Path,
    *,
    pipeline_name: str,
    results: dict[str, Any],
    completed_at: str,
) -> Path:
    """Write a top-level README for pipeline outputs."""
    lines = [
        "# OmicsClaw Pipeline Output Guide",
        "",
        "## Overview",
        "",
        f"- **Pipeline**: `{pipeline_name}`",
        f"- **Completed at**: `{completed_at}`",
        "- Open the per-step `README.md` inside each step folder for the method, parameters, and output map.",
        "- Open each step's `reproducibility/analysis_notebook.ipynb` for a code-first walkthrough.",
        "",
        "## Steps",
        "",
        "| Step | Status | Method | Output | Notebook |",
        "|------|--------|--------|--------|----------|",
    ]

    for step_name, info in results.items():
        status = "success" if info.get("success") else "failed"
        method = info.get("method") or "-"
        output_name = Path(info.get("output_dir", step_name)).name if info.get("output_dir") else "-"
        notebook_name = Path(info.get("notebook_path", "")).name if info.get("notebook_path") else "-"
        lines.append(f"| `{step_name}` | `{status}` | `{method}` | `{output_name}` | `{notebook_name}` |")

    lines.extend(["", "## Folder Contents", ""])
    for path in sorted(output_dir.iterdir(), key=lambda p: (p.is_file(), p.name.lower())):
        suffix = "/" if path.is_dir() else ""
        lines.append(f"- `{path.name}{suffix}`")

    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return readme_path
