"""Post-run output processing: rename, README, and Skill replay capsule.

After the skill subprocess exits successfully the runner needs to:

1. Optionally rename the auto-generated output directory to include the
   actual method that was used (``spatial-domains__cellcharter__20260329_063000``).
2. Write a human-readable ``README.md`` summarising what ran.
3. Emit a portable replay contract from verified execution evidence.

Pipeline runs also emit a top-level ``README.md`` that lists each step's
status / method / output — that helper lives here too so all post-run
artifact generation is in one file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from omicsclaw.common.output_claim import atomic_write_owned_output_text
from omicsclaw.common.report import (
    extract_method_name,
    load_result_json,
    write_output_readme,
)
from omicsclaw.skill.result import SkillRunAuditIdentity

from .reproducibility import write_skill_replay_capsule

from .output_ownership import (
    collect_output_claim_identities,
    is_contained_output_path,
    is_scientific_output_file,
)


def deduplicate_path(path: Path) -> Path:
    """Append ``_1``, ``_2`` ... until the path becomes unique."""
    if not path.exists():
        return path
    i = 1
    while True:
        candidate = path.with_name(f"{path.name}_{i}")
        if not candidate.exists():
            return candidate
        i += 1


def finalize_output_directory(
    out_dir: Path,
    *,
    skill_name: str,
    skill_info: dict[str, Any],
    timestamp: str,
    user_supplied_output_dir: bool,
    preferred_method: str | None = None,
    audit_identity: SkillRunAuditIdentity,
    runtime_source: str,
    demo: bool,
    input_paths: list[str] | None = None,
    forwarded_args: list[str] | None = None,
) -> tuple[Path, str | None, str, str, dict[str, Any] | None]:
    """Rename autogenerated output dirs and generate human-readable artifacts.

    Returns ``(final_dir, actual_method, readme_path, replay_path, payload)``.
    """
    payload = load_result_json(out_dir)
    actual_method = extract_method_name(payload, fallback=preferred_method)
    final_dir = out_dir

    # ADR 0035 constraint 3: the resolver names the Run directory up front; there
    # is no post-run rename. The actual method (which a skill may auto-select) is
    # recorded in ``manifest.json`` by ``run_paths.finalize_run`` and surfaced in
    # the README/replay evidence below — the directory name never changes after creation,
    # so any ``index.jsonl`` / ``manifest.json`` entry stays valid.

    replay_path = write_skill_replay_capsule(
        final_dir,
        skill_alias=skill_name,
        skill_info=skill_info,
        result_payload=payload,
        audit_identity=audit_identity,
        runtime_source=runtime_source,
        demo=demo,
        input_paths=input_paths or [],
        forwarded_args=forwarded_args or [],
    )
    readme_path = write_output_readme(
        final_dir,
        skill_alias=skill_name,
        description=skill_info.get("description", ""),
        result_payload=payload,
        preferred_method=actual_method,
        replay_path=replay_path,
    )
    return final_dir, actual_method, str(readme_path), str(replay_path), payload


def write_pipeline_readme(
    output_dir: Path,
    *,
    pipeline_name: str,
    results: dict[str, Any],
    completed_at: str,
) -> Path:
    """Write a top-level README for pipeline outputs."""
    lines = [
        "# OmicsClaw Pipeline Output Guide",
        "",
        "## Overview",
        "",
        f"- **Pipeline**: `{pipeline_name}`",
        f"- **Completed at**: `{completed_at}`",
        "- Open the per-step `README.md` inside each step folder for the method, parameters, and output map.",
        "- Use each step's `reproducibility/replay.json` as the machine-readable replay contract.",
        "",
        "## Steps",
        "",
        "| Step | Status | Method | Output | Replay |",
        "|------|--------|--------|--------|----------|",
    ]

    for step_name, info in results.items():
        status = "success" if info.get("success") else "failed"
        method = info.get("method") or "-"
        output_name = (
            Path(info.get("output_dir", step_name)).name
            if info.get("output_dir")
            else "-"
        )
        replay_name = (
            Path(info.get("replay_path", "")).name if info.get("replay_path") else "-"
        )
        lines.append(
            f"| `{step_name}` | `{status}` | `{method}` | `{output_name}` | `{replay_name}` |"
        )

    lines.extend(["", "## Folder Contents", ""])
    claim_identities = collect_output_claim_identities(output_dir)
    for path in sorted(
        (
            candidate
            for candidate in output_dir.iterdir()
            if not candidate.is_symlink()
            and is_contained_output_path(candidate, output_root=output_dir)
            and (
                candidate.is_dir()
                or is_scientific_output_file(
                    candidate,
                    output_root=output_dir,
                    claim_identities=claim_identities,
                )
            )
        ),
        key=lambda p: (p.is_file(), p.name.lower()),
    ):
        suffix = "/" if path.is_dir() else ""
        lines.append(f"- `{path.name}{suffix}`")

    return atomic_write_owned_output_text(
        output_dir / "README.md",
        output_root=output_dir,
        text="\n".join(lines) + "\n",
        label="pipeline output guide",
    )
